### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by romka777** [tony2001/leptonica#1]
roma@vm02:/usr/local/src/leptonica$ sudo ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20090626
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for Leptonica support... yes, shared
checking for Leptonica files in default path... found in /usr/local
checking for pixGetRGBPixel in -llept... no
configure: error: wrong Leptonica version (1.52+ is required) or Leptonica library not found

**Comment by romka777** [comment]
sudo aptitude install libpng12-dev libjpeg62-dev libtiff4-dev

**Comment by tony2001** [comment]
See your config.log.

On 07/21/2011 12:39 PM, romka777 wrote:

> roma@vm02:/usr/local/src/leptonica$ sudo ./configure
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /usr
> checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
> checking for PHP extension directory... /usr/lib/php5/20090626
> checking for PHP installed headers prefix... /usr/include/php5
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... re2c
> checking for re2c version... 0.13.5 (ok)
> checking for gawk... no
> checking for nawk... nawk
> checking if nawk is broken... no
> checking for Leptonica support... yes, shared
> checking for Leptonica files in default path... found in /usr/local
> checking for pixGetRGBPixel in -llept... no
> configure: error: wrong Leptonica version (1.52+ is required) or Leptonica library not found

## 

Wbr,

## Antony Dovgal

http://pinba.org - realtime profiling for PHP
